# Stage 0, "run-stage".
FROM node:lts-alpine

WORKDIR /usr/src/app/

COPY package*.json ./
RUN npm install
COPY tsconfig.json .
COPY jest.config.js .
COPY src src
COPY public public

USER node

ENTRYPOINT [ "npm", "start" ]
