declare module "design-react-kit" {
  export {
    Alert,
    Container,
    Row,
    Col,
    Navbar,
    NavbarBrand,
    NavbarToggler,
    Nav,
    NavItem,
    NavLink,
    Breadcrumb,
    BreadcrumbItem,
    Button,
    ButtonDropdown,
    ButtonGroup,
    ButtonToolbar,
    Dropdown,
    DropdownItem,
    DropdownMenu,
    DropdownToggle,
    Fade,
    Badge,
    Card,
    CardLink,
    CardGroup,
    CardDeck,
    CardColumns,
    CardBody,
    CardFooter,
    CardHeader,
    CardImg,
    CardImgOverlay,
    Carousel,
    UncontrolledCarousel,
    CarouselControl,
    CarouselItem,
    CarouselIndicators,
    CarouselCaption,
    CardSubtitle,
    CardText,
    CardTitle,
    Popover,
    PopoverBody,
    PopoverHeader,
    Progress,
    Modal,
    ModalHeader,
    ModalBody,
    ModalFooter,
    Tooltip,
    Table,
    ListGroup,
    Form,
    FormFeedback,
    // Overridden below
    // FormGroup,
    FormText,
    InputGroup,
    InputGroupAddon,
    InputGroupButtonDropdown,
    InputGroupText,
    Label,
    Media,
    // Avoid breaking changes until next major release
    Pagination,
    PaginationItem,
    PaginationLink,
    Pagination as Pager,
    PaginationItem as PagerItem,
    PaginationLink as PagerLink,
    TabContent,
    TabPane,
    Jumbotron,
    // Overridden below
    // Collapse,
    ListGroupItem,
    ListGroupItemText,
    ListGroupItemHeading,
    UncontrolledAlert,
    UncontrolledButtonDropdown,
    UncontrolledDropdown,
    UncontrolledTooltip,
    Header,
    HeaderBrand,
    HeaderContent,
    HeaderRightZone,
    Icon,
  } from "reactstrap";
}
