type: object
properties:
    soggetto:
        title: Il sottoscritto
        $ref: "definitions.yaml#/schemas/Person"
    richiedente:
        $ref: "definitions.yaml#/schemas/Person"
    domiciliato:
        $ref: "definitions.yaml#/schemas/Person"
    documento:
        properties:
            idCard:
                title: numero
                type: string
            tipo:
                title: Tipo
                type: string
                enum:
                - "Carta d'identità"
                - "SPID"
                - "Passaporto"
                - "Patente"
            rilasciato_da:
                title: Tipo
                type: string
            rilasciato_il:
                title: Tipo
                type: string
                format: date
    dichiarazione:
        properties:
            esigenze_lavoro:
                type: boolean
                title: |-
                    Comprovate esigenze lavorative
            esigenze_salute:
                type: boolean
                title: |-
                    Motivi di salute
            esigenze_altro:
                type: boolean
                title: |-
                    altri motivi ammessi dalle vigenti normative ovvero dai predetti decreti, ordinanze e altri
                    provvedimenti che definiscono le misure di prevenzione della diffusione del contagio
                    (specificare il motivo che determina lo spostamento)

            spostamento_iniziato:
                type: string
            spostamento_destinazione:
                type: string
            spostamento_motivo:
                type: string
            data:
                type: string
                format: date-time
                description: anno-mese-giorno
__filemeta:
    filename: src/pages/docs/components/multiple-forms/FormsExamples.js
    name: schema
