type: object
properties:
    SchedaAnagraficaSUAP:
      $ref: "definitions.yaml#/schemas/SchedaAnagraficaSUAP"

__filemeta:
    filename: src/pages/docs/components/multiple-forms/FormsExamples.js
    name: schema
