on: [pull_request]

jobs:
  publiccode_validation:
    runs-on: ubuntu-latest
    name: publiccode validation
    steps:
    - uses: actions/checkout@v2
    - uses: italia/publiccode-parser-action@v0.0.2-alpha
      with:
        publiccode: 'publiccode.yml'
        comment-on-pr: true
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
